Adding a translation for postgres
But it does not work
```
ERROR:  syntax error at or near "NOT"
LINE 1: CREATE DATABASE  IF NOT EXISTS "muses" /*!40100 DEFAULT CHAR...
                            ^
ERROR:  syntax error at or near "USE"
LINE 1: USE "muses";
        ^
NOTICE:  table "access_request" does not exist, skipping
DROP TABLE
ERROR:  syntax error at or near "("
LINE 2:   "access_request_id" bigint(20) unsigned NOT NULL AUTO_INCR...
```

This refs #15